export interface CountryType {
  nameEng: string;
  nameUkr: string;
}

const countryList: CountryType[] = [
  { nameEng: "Afghanistan", nameUkr: "Афганістан" },
  { nameEng: "Albania", nameUkr: "Албанія" },
  { nameEng: "Algeria", nameUkr: "Алжир" },
  { nameEng: "American Samoa", nameUkr: "Американське Самоа" },
  { nameEng: "Andorra", nameUkr: "Андорра" },
  { nameEng: "Angola", nameUkr: "Ангола" },
  { nameEng: "Anguilla", nameUkr: "Ангілья" },
  { nameEng: "Antarctica", nameUkr: "Антарктида" },
  { nameEng: "Antigua and Barbuda", nameUkr: "Антигуа і Барбуда" },
  { nameEng: "Argentina", nameUkr: "Аргентина" },
  { nameEng: "Armenia", nameUkr: "Вірменія" },
  { nameEng: "Aruba", nameUkr: "Аруба" },
  { nameEng: "Australia", nameUkr: "Австралія" },
  { nameEng: "Austria", nameUkr: "Австрія" },
  { nameEng: "Azerbaijan", nameUkr: "Азербайджан" },
  { nameEng: "Bahamas (the)", nameUkr: "Багами" },
  { nameEng: "Bahrain", nameUkr: "Бахрейн" },
  { nameEng: "Bangladesh", nameUkr: "Бангладеш" },
  { nameEng: "Barbados", nameUkr: "Барбадос" },
  { nameEng: "Belarus", nameUkr: "Білорусь" },
  { nameEng: "Belgium", nameUkr: "Бельгія" },
  { nameEng: "Belize", nameUkr: "Беліз" },
  { nameEng: "Benin", nameUkr: "Бенін" },
  { nameEng: "Bermuda", nameUkr: "Бермуди" },
  { nameEng: "Bhutan", nameUkr: "Бутан" },
  { nameEng: "Bolivia (Plurinational State of)", nameUkr: "Болівія" },
  {
    nameEng: "Bonaire, Sint Eustatius and Saba",
    nameUkr: "Бонайре, Сінт-Естатіус і Саба",
  },
  { nameEng: "Bosnia and Herzegovina", nameUkr: "Боснія і Герцеговина" },
  { nameEng: "Botswana", nameUkr: "Ботсвана" },
  { nameEng: "Bouvet Island", nameUkr: "Острів Буве" },
  { nameEng: "Brazil", nameUkr: "Бразилія" },
  {
    nameEng: "British Indian Ocean Territory (the)",
    nameUkr: "Британська територія в Індійському океані",
  },
  { nameEng: "Brunei Darussalam", nameUkr: "Бруней" },
  { nameEng: "Bulgaria", nameUkr: "Болгарія" },
  { nameEng: "Burkina Faso", nameUkr: "Буркіна-Фасо" },
  { nameEng: "Burundi", nameUkr: "Бурунді" },
  { nameEng: "Cabo Verde", nameUkr: "Кабо-Верде" },
  { nameEng: "Cambodia", nameUkr: "Камбоджа" },
  { nameEng: "Cameroon", nameUkr: "Камерун" },
  { nameEng: "Canada", nameUkr: "Канада" },
  { nameEng: "Cayman Islands (the)", nameUkr: "Кайманові Острови" },
  {
    nameEng: "Central African Republic (the)",
    nameUkr: "Центральноафриканська Республіка",
  },
  { nameEng: "Chad", nameUkr: "Чад" },
  { nameEng: "Chile", nameUkr: "Чілі" },
  { nameEng: "China", nameUkr: "Китай" },
  { nameEng: "Christmas Island", nameUkr: "Острів Різдва" },
  {
    nameEng: "Cocos (Keeling) Islands (the)",
    nameUkr: "Кокосові (Кілінг) Острови",
  },
  { nameEng: "Colombia", nameUkr: "Колумбія" },
  { nameEng: "Comoros (the)", nameUkr: "Коморські Острови" },
  {
    nameEng: "Congo (the Democratic Republic of the)",
    nameUkr: "Конго (Демократична Республіка)",
  },
  { nameEng: "Congo (the)", nameUkr: "Конго" },
  { nameEng: "Cook Islands (the)", nameUkr: "Острови Кука" },
  { nameEng: "Costa Rica", nameUkr: "Коста-Ріка" },
  { nameEng: "Croatia", nameUkr: "Хорватія" },
  { nameEng: "Cuba", nameUkr: "Куба" },
  { nameEng: "Curaçao", nameUkr: "Кюрасао" },
  { nameEng: "Cyprus", nameUkr: "Кіпр" },
  { nameEng: "Czechia", nameUkr: "Чехія" },
  { nameEng: "Côte d'Ivoire", nameUkr: "Кот-д'Івуар" },
  { nameEng: "Denmark", nameUkr: "Данія" },
  { nameEng: "Djibouti", nameUkr: "Джибуті" },
  { nameEng: "Dominica", nameUkr: "Домініка" },
  { nameEng: "Dominican Republic (the)", nameUkr: "Домініканська Республіка" },
  { nameEng: "Ecuador", nameUkr: "Еквадор" },
  { nameEng: "Egypt", nameUkr: "Єгипет" },
  { nameEng: "El Salvador", nameUkr: "Сальвадор" },
  { nameEng: "Equatorial Guinea", nameUkr: "Екваторіальна Гвінея" },
  { nameEng: "Eritrea", nameUkr: "Еритрея" },
  { nameEng: "Estonia", nameUkr: "Естонія" },
  { nameEng: "Eswatini", nameUkr: "Есватіні" },
  { nameEng: "Ethiopia", nameUkr: "Ефіопія" },
  {
    nameEng: "Falkland Islands (the) [Malvinas]",
    nameUkr: "Фолклендські острови (Мальвінські)",
  },
  { nameEng: "Faroe Islands (the)", nameUkr: "Фарерські острови" },
  { nameEng: "Fiji", nameUkr: "Фіджі" },
  { nameEng: "Finland", nameUkr: "Фінляндія" },
  { nameEng: "France", nameUkr: "Франція" },
  { nameEng: "French Guiana", nameUkr: "Французька Гвіана" },
  { nameEng: "French Polynesia", nameUkr: "Французька Полінезія" },
  {
    nameEng: "French Southern Territories (the)",
    nameUkr: "Французькі Південні території",
  },
  { nameEng: "Gabon", nameUkr: "Габон" },
  { nameEng: "Gambia (the)", nameUkr: "Гамбія" },
  { nameEng: "Georgia", nameUkr: "Грузія" },
  { nameEng: "Germany", nameUkr: "Німеччина" },
  { nameEng: "Ghana", nameUkr: "Гана" },
  { nameEng: "Gibraltar", nameUkr: "Гібралтар" },
  { nameEng: "Greece", nameUkr: "Греція" },
  { nameEng: "Greenland", nameUkr: "Ґренландія" },
  { nameEng: "Grenada", nameUkr: "Гренада" },
  { nameEng: "Guadeloupe", nameUkr: "Гваделупа" },
  { nameEng: "Guam", nameUkr: "Гуам" },
  { nameEng: "Guatemala", nameUkr: "Ґватемала" },
  { nameEng: "Guernsey", nameUkr: "Ґернсі" },
  { nameEng: "Guinea", nameUkr: "Гвінея" },
  { nameEng: "Guinea-Bissau", nameUkr: "Гвінея-Бісау" },
  { nameEng: "Guyana", nameUkr: "Гаяна" },
  { nameEng: "Haiti", nameUkr: "Гаїті" },
  {
    nameEng: "Heard Island and McDonald Islands",
    nameUkr: "Острів Герда і острови Макдональд",
  },
  { nameEng: "Holy See (the)", nameUkr: "Святий Престол" },
  { nameEng: "Honduras", nameUkr: "Гондурас" },
  { nameEng: "Hong Kong", nameUkr: "Гонконг" },
  { nameEng: "Hungary", nameUkr: "Угорщина" },
  { nameEng: "Iceland", nameUkr: "Ісландія" },
  { nameEng: "India", nameUkr: "Індія" },
  { nameEng: "Indonesia", nameUkr: "Індонезія" },
  { nameEng: "Iran (Islamic Republic of)", nameUkr: "Іран" },
  { nameEng: "Iraq", nameUkr: "Ірак" },
  { nameEng: "Ireland", nameUkr: "Ірландія" },
  { nameEng: "Isle of Man", nameUkr: "Острів Мен" },
  { nameEng: "Israel", nameUkr: "Ізраїль" },
  { nameEng: "Italy", nameUkr: "Італія" },
  { nameEng: "Jamaica", nameUkr: "Ямайка" },
  { nameEng: "Japan", nameUkr: "Японія" },
  { nameEng: "Jersey", nameUkr: "Джерсі" },
  { nameEng: "Jordan", nameUkr: "Йорданія" },
  { nameEng: "Kazakhstan", nameUkr: "Казахстан" },
  { nameEng: "Kenya", nameUkr: "Кенія" },
  { nameEng: "Kiribati", nameUkr: "Кірибаті" },
  {
    nameEng: "Korea (the Democratic People's Republic of)",
    nameUkr: "Корея (Демократична Народна Республіка)",
  },
  { nameEng: "Korea (the Republic of)", nameUkr: "Корея (Республіка)" },
  { nameEng: "Kuwait", nameUkr: "Кувейт" },
  { nameEng: "Kyrgyzstan", nameUkr: "Киргизстан" },
  {
    nameEng: "Lao People's Democratic Republic (the)",
    nameUkr: "Лаоська Народно-Демократична Республіка",
  },
  { nameEng: "Latvia", nameUkr: "Латвія" },
  { nameEng: "Lebanon", nameUkr: "Ліван" },
  { nameEng: "Lesotho", nameUkr: "Лесото" },
  { nameEng: "Liberia", nameUkr: "Ліберія" },
  { nameEng: "Libya", nameUkr: "Лівія" },
  { nameEng: "Liechtenstein", nameUkr: "Ліхтенштейн" },
  { nameEng: "Lithuania", nameUkr: "Литва" },
  { nameEng: "Luxembourg", nameUkr: "Люксембург" },
  { nameEng: "Macao", nameUkr: "Макао" },
  { nameEng: "Madagascar", nameUkr: "Мадагаскар" },
  { nameEng: "Malawi", nameUkr: "Малаві" },
  { nameEng: "Malaysia", nameUkr: "Малайзія" },
  { nameEng: "Maldives", nameUkr: "Мальдіви" },
  { nameEng: "Mali", nameUkr: "Малі" },
  { nameEng: "Malta", nameUkr: "Мальта" },
  { nameEng: "Marshall Islands (the)", nameUkr: "Маршаллові Острови" },
  { nameEng: "Martinique", nameUkr: "Мартиніка" },
  { nameEng: "Mauritania", nameUkr: "Мавританія" },
  { nameEng: "Mauritius", nameUkr: "Маврикій" },
  { nameEng: "Mayotte", nameUkr: "Майотта" },
  { nameEng: "Mexico", nameUkr: "Мексика" },
  {
    nameEng: "Micronesia (Federated States of)",
    nameUkr: "Мікронезія (Федеративні Штати)",
  },
  { nameEng: "Moldova (the Republic of)", nameUkr: "Молдова" },
  { nameEng: "Monaco", nameUkr: "Монако" },
  { nameEng: "Mongolia", nameUkr: "Монголія" },
  { nameEng: "Montenegro", nameUkr: "Чорногорія" },
  { nameEng: "Montserrat", nameUkr: "Монтсеррат" },
  { nameEng: "Morocco", nameUkr: "Марокко" },
  { nameEng: "Mozambique", nameUkr: "Мозамбік" },
  { nameEng: "Myanmar", nameUkr: "М'янма" },
  { nameEng: "Namibia", nameUkr: "Намібія" },
  { nameEng: "Nauru", nameUkr: "Науру" },
  { nameEng: "Nepal", nameUkr: "Непал" },
  { nameEng: "Netherlands (the)", nameUkr: "Нідерланди" },
  { nameEng: "New Caledonia", nameUkr: "Нова Каледонія" },
  { nameEng: "New Zealand", nameUkr: "Нова Зеландія" },
  { nameEng: "Nicaragua", nameUkr: "Нікарагуа" },
  { nameEng: "Niger (the)", nameUkr: "Нігер" },
  { nameEng: "Nigeria", nameUkr: "Нігерія" },
  { nameEng: "Niue", nameUkr: "Ніуе" },
  { nameEng: "Norfolk Island", nameUkr: "Острів Норфолк" },
  {
    nameEng: "Northern Mariana Islands (the)",
    nameUkr: "Північні Маріанські острови",
  },
  { nameEng: "Norway", nameUkr: "Норвегія" },
  { nameEng: "Oman", nameUkr: "Оман" },
  { nameEng: "Pakistan", nameUkr: "Пакистан" },
  { nameEng: "Palau", nameUkr: "Палау" },
  { nameEng: "Palestine, State of", nameUkr: "Палестина" },
  { nameEng: "Panama", nameUkr: "Панама" },
  { nameEng: "Papua New Guinea", nameUkr: "Папуа-Нова Гвінея" },
  { nameEng: "Paraguay", nameUkr: "Парагвай" },
  { nameEng: "Peru", nameUkr: "Перу" },
  { nameEng: "Philippines (the)", nameUkr: "Філіппіни" },
  { nameEng: "Pitcairn", nameUkr: "Піткерн" },
  { nameEng: "Poland", nameUkr: "Польща" },
  { nameEng: "Portugal", nameUkr: "Португалія" },
  { nameEng: "Puerto Rico", nameUkr: "Пуерто-Ріко" },
  { nameEng: "Qatar", nameUkr: "Катар" },
  { nameEng: "Republic of North Macedonia", nameUkr: "Північна Македонія" },
  { nameEng: "Romania", nameUkr: "Румунія" },
  { nameEng: "Russian Federation (the)", nameUkr: "Російська Федерація" },
  { nameEng: "Rwanda", nameUkr: "Руанда" },
  { nameEng: "Réunion", nameUkr: "Реюньйон" },
  { nameEng: "Saint Barthélemy", nameUkr: "Сен-Бартельмі" },
  {
    nameEng: "Saint Helena, Ascension and Tristan da Cunha",
    nameUkr: "Свята Єлена, Вознесіння та Трістан-да-Кунья",
  },
  { nameEng: "Saint Kitts and Nevis", nameUkr: "Сент-Кіттс і Невіс" },
  { nameEng: "Saint Lucia", nameUkr: "Сент-Люсія" },
  {
    nameEng: "Saint Martin (French part)",
    nameUkr: "Сен-Мартен (французька частина)",
  },
  { nameEng: "Saint Pierre and Miquelon", nameUkr: "Сен-П'єр і Мікелон" },
  {
    nameEng: "Saint Vincent and the Grenadines",
    nameUkr: "Сент-Вінсент і Гренадини",
  },
  { nameEng: "Samoa", nameUkr: "Самоа" },
  { nameEng: "San Marino", nameUkr: "Сан-Марино" },
  { nameEng: "Sao Tome and Principe", nameUkr: "Сан-Томе і Прінсіпі" },
  { nameEng: "Saudi Arabia", nameUkr: "Саудівська Аравія" },
  { nameEng: "Senegal", nameUkr: "Сенегал" },
  { nameEng: "Serbia", nameUkr: "Сербія" },
  { nameEng: "Seychelles", nameUkr: "Сейшельські Острови" },
  { nameEng: "Sierra Leone", nameUkr: "Сьєрра-Леоне" },
  { nameEng: "Singapore", nameUkr: "Сінгапур" },
  {
    nameEng: "Sint Maarten (Dutch part)",
    nameUkr: "Сінт-Маартен (голландська частина)",
  },
  { nameEng: "Slovakia", nameUkr: "Словаччина" },
  { nameEng: "Slovenia", nameUkr: "Словенія" },
  { nameEng: "Solomon Islands", nameUkr: "Соломонові Острови" },
  { nameEng: "Somalia", nameUkr: "Сомалі" },
  { nameEng: "South Africa", nameUkr: "Південна Африка" },
  {
    nameEng: "South Georgia and the South Sandwich Islands",
    nameUkr: "Південна Джорджія і Південні Сандвічеві острови",
  },
  { nameEng: "South Sudan", nameUkr: "Південний Судан" },
  { nameEng: "Spain", nameUkr: "Іспанія" },
  { nameEng: "Sri Lanka", nameUkr: "Шрі-Ланка" },
  { nameEng: "Sudan (the)", nameUkr: "Судан" },
  { nameEng: "Suriname", nameUkr: "Сурінам" },
  { nameEng: "Svalbard and Jan Mayen", nameUkr: "Шпіцберген і Ян-Маєн" },
  { nameEng: "Sweden", nameUkr: "Швеція" },
  { nameEng: "Switzerland", nameUkr: "Швейцарія" },
  { nameEng: "Syrian Arab Republic", nameUkr: "Сирійська Арабська Республіка" },
  { nameEng: "Taiwan", nameUkr: "Тайвань" },
  { nameEng: "Tajikistan", nameUkr: "Таджикистан" },
  {
    nameEng: "Tanzania, United Republic of",
    nameUkr: "Танзанія, Об'єднана Республіка",
  },
  { nameEng: "Thailand", nameUkr: "Таїланд" },
  { nameEng: "Timor-Leste", nameUkr: "Тімор-Лешті" },
  { nameEng: "Togo", nameUkr: "Того" },
  { nameEng: "Tokelau", nameUkr: "Токелау" },
  { nameEng: "Tonga", nameUkr: "Тонга" },
  { nameEng: "Trinidad and Tobago", nameUkr: "Тринідад і Тобаго" },
  { nameEng: "Tunisia", nameUkr: "Туніс" },
  { nameEng: "Turkey", nameUkr: "Туреччина" },
  { nameEng: "Turkmenistan", nameUkr: "Туркменістан" },
  {
    nameEng: "Turks and Caicos Islands (the)",
    nameUkr: "Острови Теркс і Кайкос",
  },
  { nameEng: "Tuvalu", nameUkr: "Тувалу" },
  { nameEng: "Uganda", nameUkr: "Уганда" },
  { nameEng: "Ukraine", nameUkr: "Україна" },
  {
    nameEng: "United Arab Emirates (the)",
    nameUkr: "Об'єднані Арабські Емірати",
  },
  {
    nameEng: "United Kingdom of Great Britain and Northern Ireland (the)",
    nameUkr: "Об'єднане Королівство Великої Британії та Північної Ірландії",
  },
  {
    nameEng: "United States Minor Outlying Islands (the)",
    nameUkr: "Малі Віддалені Острови Сполучених Штатів",
  },
  {
    nameEng: "United States of America (the)",
    nameUkr: "Сполучені Штати Америки",
  },
  { nameEng: "Uruguay", nameUkr: "Уругвай" },
  { nameEng: "Uzbekistan", nameUkr: "Узбекистан" },
  { nameEng: "Vanuatu", nameUkr: "Вануату" },
  {
    nameEng: "Venezuela (Bolivarian Republic of)",
    nameUkr: "Венесуела (Боліваріанська Республіка)",
  },
  { nameEng: "Viet Nam", nameUkr: "В'єтнам" },
  {
    nameEng: "Virgin Islands (British)",
    nameUkr: "Віргінські острови (Британські)",
  },
  { nameEng: "Virgin Islands (U.S.)", nameUkr: "Віргінські острови (США)" },
  { nameEng: "Wallis and Futuna", nameUkr: "Уолліс і Футуна" },
  { nameEng: "Western Sahara", nameUkr: "Західна Сахара" },
  { nameEng: "Yemen", nameUkr: "Ємен" },
  { nameEng: "Zambia", nameUkr: "Замбія" },
  { nameEng: "Zimbabwe", nameUkr: "Зімбабве" },
  { nameEng: "Åland Islands", nameUkr: "Аландські острови" },
];

export default countryList;
